### ISSUE TITLE
Can't run this task on multiple files

### ISSUE THREAD

**Issue by pixelbandito** [StickyCube/grunt-replace-attribute#1]
Using a list of destination and src or a files object with `expand: true` results in the following error:
```
Error Parsing html - Error: write after end
```

**Comment by StickyCube** [comment]
Hey @pixelbandito 

Just had a quick look and managed to reproduce your issue.
I've published a new release v1.0.1 and it seems to work for me. Let me know if it solves your problem.

**Comment by pixelbandito** [comment]
All fixed. Thanks! 

I submitted pull request #2 to add a test to the Gruntfile for multi-file replacement. I don't know if that's overkill.

**Comment by StickyCube** [comment]
Thanks! I was going to add some yesterday but got distracted by something else.
